### ISSUE TITLE
"Capacity 119%" in your screenshot

### ISSUE THREAD

**Issue by CaledoniaProject** [coldfix/awesome.battery-widget#37]
In your screenshot the battery capacity is 119%, is that normal?

**Comment by coldfix** [comment]
Hi! Yes, it seems that battery capacities are quite frequently reported as higher than the design value. Compare the files

- `/sys/class/power_supply/BAT0/energy_full` or `charge_full` (current estimated capacity)
- `/sys/class/power_supply/BAT0/energy_full_design` or `charge_full_design` (design value)

I'm not sure exactly why this is the case, but I could image that it could be either due to safety margins implemented by the manufacturers (in order not to advertise a higher number than they can deliver, for legal reasons), or due to incorrect capacity estimates.
